#!/usr/bin/env python3
import argparse
from collections import defaultdict
import hashlib
import os
import re
import sys

T2SFILES_HOME = os.environ.get('T2SFILES_HOME')
if not T2SFILES_HOME:
    sys.stderr.write('T2SFILES_HOME is not set; aborting\n')
    sys.exit(1)
if not os.path.isdir(T2SFILES_HOME):
    sys.stderr.write(f'T2SFILES_HOME={T2SFILES_HOME}; directory not found\n')
    sys.exit(1)

LIBT2S_DIR = f'{T2SFILES_HOME}/tools'
if not os.path.isdir(LIBT2S_DIR):
    sys.stderr.write(f'{LIBT2S_DIR}: directory not found\n')
    sys.exit(1)
sys.path.insert(0, LIBT2S_DIR)

from libt2s import SPECTRUM_TAPES, get_tapes

HEADER_HTML = """
<!DOCTYPE html>
<html>
<head>
<title>TZX block types</title>
<meta charset="utf-8" />
<style>
body { color: black; background-color: #a0a0a0; }
th { text-align: left; }
td { vertical-align: top; overflow-wrap: anywhere }
</style>
</head>
<body>
<table>
<tr><th>ID</th><th width="400">Game</th><th width="400">Tape</th><th>TZX block types</th></tr>
""".lstrip()

FOOTER_HTML = """
</table>
</body>
</html>
""".lstrip()

HTML = 'tzxblocks.html'

TAPINFO_DIR = f'{SPECTRUM_TAPES}/tapinfo'

def run():
    tapes = get_tapes()
    tzx_blocks = {}
    for root, subdirs, files in sorted(os.walk(TAPINFO_DIR)):
        for fname in sorted(files):
            if not fname.lower().endswith('.tzx.txt'):
                continue
            tapinfo_file = os.path.join(root, fname)
            tape_file = tapinfo_file.replace(TAPINFO_DIR, SPECTRUM_TAPES)[:-4]
            if not os.path.isfile(tape_file):
                print(f'WARNING: {tape_file}: file not found', file=sys.stderr)
                continue
            with open(tape_file, 'rb') as f:
                md5 = hashlib.md5(f.read()).hexdigest()
            if md5 not in tapes:
                continue
            blocks = set()
            with open(tapinfo_file) as f:
                for line in f:
                    s_line = line.rstrip()
                    if re.match(r'^[0-9]*:.*\(0x[0-9A-F][0-9A-F]\)$', s_line):
                        blocks.add(s_line[-5:-1])
            tzx_blocks[md5] = {
                'name': os.path.basename(tape_file),
                'blocks': ' '.join(sorted(blocks)),
                'game': tapes[md5]['game'],
                'iid': tapes[md5]['infoseek']
            }

    tapes_by_iid = defaultdict(list)
    tcount = len(tzx_blocks)
    for tape in sorted(tzx_blocks.values(), key=lambda t: t['iid']):
        tapes_by_iid[tape['iid']].append(tape)
    with open(HTML, 'w') as f:
        f.write(HEADER_HTML)
        for iid in sorted(tapes_by_iid):
            tapes = tapes_by_iid[iid]
            rowspan = '' if len(tapes) == 1 else f' rowspan="{len(tapes)}"'
            url = f'https://spectrumcomputing.co.uk/entry/{iid}'
            game = tapes[0]['game']
            name = tapes[0]['name']
            blocks = tapes[0]['blocks']
            f.write(f'<tr><td{rowspan}><a href="{url}">{iid}</a></td><td{rowspan}>{game}</td><td>{name}</td><td>{blocks}</td></tr>\n')
            for tape in tapes[1:]:
                name = tape['name']
                blocks = tape['blocks']
                f.write(f'<tr><td>{name}</td><td>{blocks}</td></tr>\n')
        f.write(FOOTER_HTML)
    print(f'Wrote {HTML} ({tcount} tapes)')

parser = argparse.ArgumentParser(
    usage='%(prog)s',
    description=f"Write an HTML document that lists TZX blocks used by each tape for which there is a tapinfo file in {TAPINFO_DIR}. "
                "The tapinfo files are generated by gen-tapinfo.sh.",
    add_help=False
)
namespace, unknown_args = parser.parse_known_args()
if unknown_args:
    parser.exit(2, parser.format_help())
run()
