#!/usr/bin/env python3
import argparse
import os

def run(compilations_txt, uploaded_dir):
   compilations = {}
   with open(compilations_txt) as f:
       for line in f:
           s_line = line.rstrip()
           if s_line.startswith('00'):
               zxdb_id = s_line[:7]
               compilations[zxdb_id] = (s_line[8:], [])
           else:
               compilations[zxdb_id][1].append(s_line)

   for d in os.listdir(uploaded_dir):
       zxdb_id = d[:7]
       if zxdb_id in compilations:
           del compilations[zxdb_id]

   with open(compilations_txt, 'w') as f:
      for zxdb_id, (name, contents) in compilations.items():
          f.write(f'{zxdb_id} {name}\n')
          for line in contents:
              f.write(f'{line}\n')

parser = argparse.ArgumentParser(
    usage='%(prog)s COMPILATIONS_TXT UPLOADED_DIR',
    description="Remove compilations from COMPILATIONS_TXT (generated by magazine-tapes.py) "
                "that appear in UPLOADED_DIR.",
    add_help=False
)
parser.add_argument('compilations', help=argparse.SUPPRESS, nargs='?')
parser.add_argument('uploaded', help=argparse.SUPPRESS, nargs='?')
namespace, unknown_args = parser.parse_known_args()
if unknown_args or not namespace.uploaded:
    parser.exit(2, parser.format_help())
run(namespace.compilations, namespace.uploaded)
